"""initial schema

Revision ID: 95b6f8f3a63b
Revises: 
Create Date: 2026-10-02 11:44:31.739359+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '95b6f8f3a63b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('active', 'disabled', 'deleted')", name='ck_endpoints_state'),
    sa.CheckConstraint("url ~ '^https?://'", name='ck_endpoints_url_scheme'),
    sa.CheckConstraint('length(name) > 0', name='ck_endpoints_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_endpoints_state', 'webhook_endpoints', ['state'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'delivered', 'dead_letter')", name='ck_events_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_events_attempt_count'),
    sa.CheckConstraint('length(event_type) > 0', name='ck_events_event_type_not_empty'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_events_max_attempts'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_id', 'idempotency_key', name='uq_events_endpoint_idempotency')
    )
    op.create_index('ix_events_endpoint_created', 'events', ['endpoint_id', 'created_at'], unique=False)
    op.create_index('ix_events_status_created', 'events', ['status', 'created_at'], unique=False)
    op.create_table('delivery_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('recoveries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_snippet', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state <> 'in_progress' OR (lease_expires_at IS NOT NULL AND worker_id IS NOT NULL)", name='ck_attempts_lease_required'),
    sa.CheckConstraint("state IN ('pending', 'in_progress', 'succeeded', 'failed')", name='ck_attempts_state'),
    sa.CheckConstraint("state NOT IN ('succeeded', 'failed') OR finished_at IS NOT NULL", name='ck_attempts_finished_required'),
    sa.CheckConstraint('attempt_number >= 1', name='ck_attempts_number'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'attempt_number', name='uq_attempts_event_number')
    )
    op.create_index('ix_attempts_claimable', 'delivery_attempts', ['scheduled_at'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_index('ix_attempts_lease', 'delivery_attempts', ['lease_expires_at'], unique=False, postgresql_where=sa.text("state = 'in_progress'"))
    op.create_index('uq_attempts_active_per_event', 'delivery_attempts', ['event_id'], unique=True, postgresql_where=sa.text("state IN ('pending', 'in_progress')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attempts_active_per_event', table_name='delivery_attempts', postgresql_where=sa.text("state IN ('pending', 'in_progress')"))
    op.drop_index('ix_attempts_lease', table_name='delivery_attempts', postgresql_where=sa.text("state = 'in_progress'"))
    op.drop_index('ix_attempts_claimable', table_name='delivery_attempts', postgresql_where=sa.text("state = 'pending'"))
    op.drop_table('delivery_attempts')
    op.drop_index('ix_events_status_created', table_name='events')
    op.drop_index('ix_events_endpoint_created', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_endpoints_state', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    # ### end Alembic commands ###
